CREATE DATABASE DEMO_BANGLUONG
GO
USE DEMO_BANGLUONG
GO

CREATE TABLE BANGLUONG
(
MATHE NVARCHAR(50) PRIMARY KEY,
HOVATEN NVARCHAR(50),
NGHENGHIEP NVARCHAR(50),
VITRI NVARCHAR(50),
THANHTICH NVARCHAR(50),
TIENTHUONGTT FLOAT,
PHUCAP NVARCHAR(50),
TIENPC DECIMAL,
LUONGCB DECIMAL,
LUONGTHUCLINH DECIMAL
)
GO
