CREATE DATABASE DEMO_DOIMATKHAU
GO
USE DEMO_DOIMATKHAU
GO

CREATE TABLE DOIMATKHAU
(
TENTAIKHOAN NVARCHAR(50),
MATKHAUCU NVARCHAR(50),
MATKHAUMOI NVARCHAR(50),
NHAPLAIMATKHAUMOI NVARCHAR(50)
)
GO

INSERT INTO DOIMATKHAU (TENTAIKHOAN, MATKHAUCU)
VALUES ('Nhom5', '123456')