CREATE DATABASE DEMO_HOPDONG
GO
USE DEMO_HOPDONG
GO

CREATE TABLE HOPDONG
(
ID NVARCHAR(50) PRIMARY KEY,
HOVATEN NVARCHAR(50),
QUOCTICH NVARCHAR(50),
SDT NVARCHAR(50),
CMND NVARCHAR(50),
DIACHI NVARCHAR(50),
NGAYKY DATETIME,
THOIHAN DATETIME,
LOAIHD NVARCHAR(50),
GIATRIHD DECIMAL
)
GO