CREATE DATABASE NHATAITRO
GO

USE NHATAITRO
GO

CREATE TABLE TBLNHATAITRO
(
MANHATAITRO NVARCHAR(50) PRIMARY KEY NOT NULL,
TENNHATAITRO NVARCHAR(100) NOT NULL,
LOAIHOPDONG NVARCHAR(100) NOT NULL,
GIATRIHOPDONG NVARCHAR(50) NOT NULL,
THONGTINLIENHE NVARCHAR(100) NOT NULL,
THOIGIANHOPDONG NVARCHAR(50) NOT NULL
)
GO