CREATE DATABASE THANHTICH
GO

USE THANHTICH
GO

CREATE TABLE TBLTHANHTICH
(
MAGIAIDAU NVARCHAR(50) PRIMARY KEY NOT NULL,
NAM NVARCHAR(50) NOT NULL,
GIAIDAU NVARCHAR(100) NOT NULL,
THANHTICHDATDUOC NVARCHAR(50) NOT NULL,
NGAYDATGIAI NVARCHAR(50) NOT NULL,

)
GO