CREATE DATABASE TRANGTHIETBI
GO

USE TRANGTHIETBI
GO

CREATE TABLE TBLTRANGTHIETBI
(
MACUNGCAP NVARCHAR(50) PRIMARY KEY NOT NULL,
TRANGTHIETBI NVARCHAR(50) NOT NULL,
SOLUONG NVARCHAR(50) NOT NULL,
DONGIA NVARCHAR(50) NOT NULL,
NGAYCUNGCAP DATETIME NOT NULL,
TONGCHIPHI NVARCHAR(50) NOT NULL,
)
GO